package com.focus3.app.data.repository

import android.content.Context
import android.content.Intent
import android.util.Log
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.tasks.await
import javax.inject.Inject
import javax.inject.Singleton

/**
 * 🔐 Firebase Authentication Repository
 * Manages Google Sign-In flow and Firebase Auth state.
 */
@Singleton
class AuthRepository @Inject constructor(
    @ApplicationContext private val context: Context
) {
    private val firebaseAuth: FirebaseAuth = FirebaseAuth.getInstance()

    private val _currentUser = MutableStateFlow(firebaseAuth.currentUser)
    val currentUser: StateFlow<FirebaseUser?> = _currentUser.asStateFlow()

    init {
        // Listen for auth state changes
        firebaseAuth.addAuthStateListener { auth ->
            _currentUser.value = auth.currentUser
        }
    }

    /**
     * Check if a user is currently signed in.
     */
    fun isLoggedIn(): Boolean = firebaseAuth.currentUser != null

    /**
     * Get the current user's UID, or null if not signed in.
     */
    fun getCurrentUid(): String? = firebaseAuth.currentUser?.uid

    /**
     * Build a GoogleSignInClient configured for Firebase Auth.
     * Uses the default_web_client_id auto-generated by google-services.json.
     */
    fun getGoogleSignInClient(): GoogleSignInClient {
        val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestIdToken(context.getString(com.focus3.app.R.string.default_web_client_id))
            .requestEmail()
            .build()
        return GoogleSignIn.getClient(context, gso)
    }

    /**
     * Get the Sign-In intent to launch the Google account picker.
     */
    fun getSignInIntent(): Intent = getGoogleSignInClient().signInIntent

    /**
     * Exchange a Google ID token for a Firebase credential and sign in.
     * @return Result.success with the FirebaseUser, or Result.failure with the exception.
     */
    suspend fun firebaseAuthWithGoogle(idToken: String): Result<FirebaseUser> {
        return try {
            val credential = GoogleAuthProvider.getCredential(idToken, null)
            val authResult = firebaseAuth.signInWithCredential(credential).await()
            val user = authResult.user
            if (user != null) {
                Log.d(TAG, "Firebase sign-in successful: ${user.email}")
                Result.success(user)
            } else {
                Result.failure(Exception("Sign-in succeeded but user is null"))
            }
        } catch (e: Exception) {
            Log.e(TAG, "Firebase sign-in failed: ${e.message}")
            Result.failure(e)
        }
    }

    /**
     * Sign out from both Firebase and Google.
     */
    suspend fun signOut() {
        try {
            // Sign out from Google first (clears cached account selection)
            getGoogleSignInClient().signOut().await()
            // Then sign out from Firebase
            firebaseAuth.signOut()
            Log.d(TAG, "Signed out successfully")
        } catch (e: Exception) {
            Log.e(TAG, "Error during sign-out: ${e.message}")
            // Firebase signOut is synchronous and won't fail,
            // but Google signOut might. Still clear Firebase state.
            firebaseAuth.signOut()
        }
    }

    companion object {
        private const val TAG = "AuthRepository"
    }
}
