package com.focus3.app.util

import kotlin.random.Random

object QuotesData {
    
    // 1000 BEST MOTIVATIONAL QUOTES
    val motivationalQuotes = listOf(
        // Success & Achievement (1-100)
        "Success is not final, failure is not fatal: it is the courage to continue that counts. 🏆",
        "The only way to do great work is to love what you do. ❤️",
        "Believe you can and you're halfway there. 🌟",
        "Your only limit is you. 🚀",
        "Dream it. Wish it. Do it. ✅",
        "The secret of getting ahead is getting started. 🗝️",
        "It always seems impossible until it's done. 🏔️",
        "Don't watch the clock; do what it does. Keep going. ⏰",
        "Quality is not an act, it is a habit. ✨",
        "Start where you are. Use what you have. Do what you can. 🎯",
        "The best way to predict your future is to create it. 🔮",
        "Setting goals is the first step in turning the invisible into the visible. 🕯️",
        "You are never too old to set another goal or to dream a new dream. 🌲",
        "The way to get started is to quit talking and begin doing. 🗣️",
        "Strive for progress, not perfection. 📈",
        "Action is the foundational key to all success. 🔑",
        "Motivation is what gets you started. Habit is what keeps you going. 🔄",
        "Your talent determines what you can do. Your motivation determines how much you're willing to do. 💡",
        "Hardships often prepare ordinary people for an extraordinary destiny. 💎",
        "I find that the harder I work, the more luck I seem to have. 🍀",
        "Success usually comes to those who are too busy to be looking for it. 🐝",
        "The only place where success comes before work is in the dictionary. 📖",
        "Opportunities don't happen. You create them. 🛠️",
        "I never dreamed about success, I worked for it. 💪",
        "Don't be afraid to give up the good to go for the great. 🚀",
        "Stop doubting yourself. Work hard and make it happen. 👊",
        "Champions keep playing until they get it right. 🏅",
        "Success is the sum of small efforts, repeated day-in and day-out. 🔁",
        "Great things are not done by impulse, but by a series of small things brought together. 🏗️",
        "If you can dream it, you can do it. 🎆",
        "Identify your targets and move towards them. 🏹",
        "Energy and persistence conquer all things. ⚡",
        "Keep your face always toward the sunshine—and shadows will fall behind you. ☀️",
        "The only limit to our realization of tomorrow will be our doubts of today. 🌅",
        "The future starts today, not tomorrow. 📅",
        "A goal without a plan is just a wish. 📝",
        "Fall seven times, stand up eight. 🆙",
        "The road to success is always under construction. 🚧",
        "Success consists of going from failure to failure without loss of enthusiasm. 😃",
        "Change your life today. Don't gamble on the future, act now. ⚡",
        "Life is 10% what happens to me and 90% of how I react to it. 🧠",
        "Optimism is the faith that leads to achievement. 🕊️",
        "We may encounter many defeats but we must not be defeated. 🛡️",
        "Everything you've ever wanted is on the other side of fear. 🏔️",
        "Success is getting what you want. Happiness is wanting what you get. 😊",
        "Victory belongs to the most persevering. 🏆",
        "Your future self is thanking you right now. 🌟",
        "Discipline is the bridge between goals and accomplishment. 🌉",
        "Don't stop when you're tired. Stop when you're done. 🏁",
        "The pain of discipline is far less than the pain of regret. 💪",
        
        // Perseverance & Strength (51-150)
        "Work hard in silence, let your success be your noise. 🔇",
        "Stay hungry, stay foolish. 🍎",
        "Be the change that you wish to see in the world. 🌍",
        "The best time to start was yesterday. The next best time is now. ⏰",
        "Success is a journey, not a destination. 🛤️",
        "Do one thing every day that scares you. 🦁",
        "What you get by achieving your goals is not as important as what you become. 🦋",
        "Believe in yourself! Have faith in your abilities! 🌟",
        "Life is short, and it is up to you to make it sweet. 🍭",
        "Keep calm and carry on. 👑",
        "Dream big and dare to fail. 🚀",
        "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. 🥊",
        "Don't let yesterday take up too much of today. ⏳",
        "You learn more from failure than from success. Don't let it stop you. 🏫",
        "If you are working on something you care about, you don't have to be pushed. 🌬️",
        "People who are crazy enough to think they can change the world are the ones who do. 🌎",
        "Knowing is not enough; we must apply. Wishing is not enough; we must do. 🛠️",
        "Imagine your life is perfect in every respect; what would it look like? 🌈",
        "We generate fears while we sit. We overcome them by action. 🏃",
        "Whether you think you can or think you can't, you're right. 🧠",
        "Security is mostly a superstition. Life is either a daring adventure or nothing. ⛰️",
        "The man who has confidence in himself gains the confidence of others. 🤝",
        "What we achieve inwardly will change outer reality. 🧘",
        "The only real failure in life is not to be true to the best one knows. 💎",
        "Creativity is intelligence having fun. 🎨",
        "Everything has beauty, but not everyone sees it. ✨",
        "The mind is everything. What you think you become. 🧠",
        "The best revenge is massive success. 🔥",
        "The only thing we have to fear is fear itself. 🛡️",
        "Life is what happens when you're busy making other plans. 🎢",
        "Get busy living or get busy dying. 🌅",
        "You only live once, but if you do it right, once is enough. 🌟",
        "To be yourself in a world that is constantly trying to make you something else is a great accomplishment. 🦄",
        "Happiness is not something ready made. It comes from your own actions. 😊",
        "Do what you can, with what you have, where you are. 📍",
        "The only way to have a friend is to be one. 🤝",
        "In the end, it's not the years in your life that count. It's the life in your years. 🕯️",
        "You must be the change you wish to see in the world. 🌍",
        "To live is the rarest thing in the world. Most people exist, that is all. 🌬️",
        "The purpose of our lives is to be happy. 😊",
        "Life is either a daring adventure or nothing at all. 🎢",
        "You have within you right now, everything you need to deal with whatever the world can throw at you. 🛡️",
        "The greatest glory in living lies not in never falling, but in rising every time we fall. 📈",
        "Your time is limited, don't waste it living someone else's life. ⌛",
        "Persistence is the key to all treasures. 🗝️",
        "In the middle of every difficulty lies opportunity. 💡",
        "The harder the conflict, the more glorious the triumph. 🏆",
        "Strength does not come from winning. Your struggles develop your strengths. 💪",
        "It does not matter how slowly you go as long as you do not stop. 🐢",
        "Courage is not the absence of fear, but rather the action in spite of fear. 🦁",
        
        // Mindset & Growth (151-250)
        "The mind is not a vessel to be filled, but a fire to be kindled. 🔥",
        "Education is the most powerful weapon which you can use to change the world. 📚",
        "Be yourself; everyone else is already taken. 🦋",
        "In three words I can sum up everything I've learned about life: it goes on. ⏳",
        "Stay positive, work hard, make it happen. ⭐",
        "Don't count the days, make the days count. 📅",
        "Tough times never last, but tough people do. 💪",
        "The comeback is always stronger than the setback. 🔄",
        "You are capable of amazing things. ✨",
        "Make today so awesome that yesterday gets jealous. 🌟",
        "Be so good they can't ignore you. 🎯",
        "Small steps every day lead to big changes. 👣",
        "Your vibe attracts your tribe. 🤝",
        "Embrace the glorious mess that you are. 🌈",
        "Life begins at the end of your comfort zone. 🚀",
        "Inhale confidence, exhale doubt. 🌬️",
        "You didn't come this far to only come this far. 🏃",
        "Make yourself a priority. 👑",
        "Stop waiting for Friday, for summer, for someone to fall in love with you. 💕",
        "Everything you need is already inside you. Get started. 🔑",
        "Be the energy you want to attract. ⚡",
        "Surround yourself with only people who are going to lift you higher. 🎈",
        "If it doesn't challenge you, it doesn't change you. 🔄",
        "The expert in anything was once a beginner. 🌱",
        "Be fearless in the pursuit of what sets your soul on fire. 🔥",
        "Your limitation—it's only your imagination. 🎨",
        "Push yourself, because no one else is going to do it for you. 🏋️",
        "Sometimes later becomes never. Do it now. ⏰",
        "Great things never came from comfort zones. 🏔️",
        "Dream bigger. Do bigger. 🚀",
        "Don't stop until you're proud. 🏆",
        "The key to success is to focus on goals, not obstacles. 🔑",
        "Hustle until your haters ask if you're hiring. 💼",
        "Your potential is endless. 🌊",
        "Wake up with determination. Go to bed with satisfaction. 🌅",
        "It's going to be hard, but hard does not mean impossible. 🏔️",
        "You are stronger than you think. 💪",
        "Little things make big days. ✨",
        "It's not a dream if it's real. 🌟",
        "Good things come to people who work their asses off. 🔥",
        "Don't tell people your plans. Show them your results. 🏆",
        "Work until your bank account looks like a phone number. 💰",
        "Stay focused and extra sparkly. ✨",
        "You are the CEO of your life. 👔",
        "Success is not for the lazy. 🏃",
        "Make it happen. Shock everyone. ⚡",
        "Turn your wounds into wisdom. 🧠",
        "Work hard, stay humble. 🙏",
        "Prove them wrong. 💪",
        "Go the extra mile. It's never crowded. 🛤️",
        
        // Focus & Productivity (251-350)
        "Focus on being productive instead of busy. 🎯",
        "Do something today that your future self will thank you for. 🌅",
        "The difference between ordinary and extraordinary is that little extra. ⭐",
        "Your habits will determine your future. 🔄",
        "Work smart. Get things done. No excuses. ⚡",
        "Make each day your masterpiece. 🎨",
        "Discipline equals freedom. 🗝️",
        "First we form habits, then they form us. 🔄",
        "The successful warrior is the average man with laser-like focus. 🎯",
        "Concentrate all your thoughts upon the work at hand. 🧠",
        "Starve your distractions and feed your focus. 📵",
        "You can't have a million-dollar dream with a minimum-wage work ethic. 💰",
        "Where focus goes, energy flows. ⚡",
        "What you do today can improve all your tomorrows. 🌅",
        "Don't wait for opportunity. Create it. 🛠️",
        "Time is what we want most, but what we use worst. ⏰",
        "Eliminate the time between the idea and the act, and your dreams will become realities. 💭",
        "Take care of the minutes; the hours will take care of themselves. ⏱️",
        "Lost time is never found again. ⏳",
        "The secret of your success is found in your daily routine. 📅",
        "Success doesn't just find you. You have to go out and get it. 🏃",
        "Your focus determines your reality. 🎯",
        "A dream does not become reality through magic; it takes sweat and determination. 💦",
        "Don't wish it were easier. Wish you were better. 💪",
        "You don't have to be great to start, but you have to start to be great. 🚀",
        "The only way to achieve the impossible is to believe it is possible. 🌟",
        "What seems impossible today will become your warm-up tomorrow. 🔥",
        "Focus on the step in front of you, not the whole staircase. 👣",
        "You are what you do, not what you say you'll do. ✅",
        "Excellence is not a skill. It's an attitude. 🏆",
        "Don't limit your challenges. Challenge your limits. 🏔️",
        "The best project you'll ever work on is you. 🌟",
        "Stay committed to your decisions, but stay flexible in your approach. 🔄",
        "Progress is progress, no matter how small. 📈",
        "You don't have to see the whole staircase, just take the first step. 👣",
        "Success is walking from failure to failure with no loss of enthusiasm. 😃",
        "If you're not moving forward, you're falling behind. 🏃",
        "The price of success is hard work and determination. 💪",
        "Focus, commitment, and dedication are the keys to success. 🔑",
        "Results happen over time, not overnight. Work hard, stay consistent and be patient. ⏳",
        "Never give up on something you really want. 🎯",
        "Be stubborn about your goals and flexible about your methods. 🔄",
        "Today I will do what others won't, so tomorrow I can accomplish what others can't. 🏆",
        "Success is liking yourself, liking what you do, and liking how you do it. 😊",
        "The greater the obstacle, the more glory in overcoming it. 🏔️",
        "There are no secrets to success. It is preparation, hard work, and learning from failure. 📚",
        "Success loves speed. Delay kills dreams. ⚡",
        "Execution beats strategy every time. ✅",
        "Less talk, more action. 🏃",
        "Stay hungry, stay humble. 🙏",
        
        // Courage & Risk (351-450)
        "Take the risk or lose the chance. 🎲",
        "Leap and the net will appear. 🦘",
        "Ships are safe in harbor, but that's not what ships are built for. ⛵",
        "Fortune favors the bold. 🦁",
        "In a gentle way, you can shake the world. 🌍",
        "Don't let what you cannot do interfere with what you can do. 🎯",
        "The only impossible journey is the one you never begin. 🚀",
        "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. ❤️",
        "Your life does not get better by chance, it gets better by change. 🔄",
        "Be brave enough to suck at something new. 🌱",
        "Fear kills more dreams than failure ever will. 😱",
        "Feel the fear and do it anyway. 💪",
        "Nothing will work unless you do. 🛠️",
        "You miss 100% of the shots you don't take. 🏀",
        "The biggest risk is not taking any risk. 🎲",
        "If you want something you've never had, you must be willing to do something you've never done. 🆕",
        "Scared money don't make money. 💰",
        "Risk more than others think is safe. Dream more than others think is practical. 💭",
        "A smooth sea never made a skilled sailor. ⛵",
        "When nothing is sure, everything is possible. 🌈",
        "The cave you fear to enter holds the treasure you seek. 💎",
        "Be bold, be courageous, be your best. 🦁",
        "Be so bold that people wonder what you'll achieve next. ⭐",
        "One day the risk to remain tight in a bud was more painful than the risk to bloom. 🌸",
        "Who dares wins. 🏆",
        "Only those who dare to fail greatly can ever achieve greatly. 🚀",
        "Adventure may hurt you, but monotony will kill you. 🎢",
        "Life is inherently risky. There is only one big risk you should avoid: the risk of doing nothing. 🛤️",
        "Security is a false god. Begin making sacrifices to it and you are lost. 🗡️",
        "You can't discover new oceans unless you have the courage to lose sight of the shore. 🌊",
        "Be fearless. 🦁",
        "Take chances. Make mistakes. That's how you grow. 🌱",
        "What would you attempt to do if you knew you could not fail? 🤔",
        "Run towards your fears. Embrace them. 🏃",
        "Do the thing you fear and the death of fear is certain. 💀",
        "Boldness has genius, power, and magic in it. ✨",
        "The brave may not live forever, but the cautious do not live at all. ⏳",
        "It's better to live one day as a lion than 100 years as a sheep. 🦁",
        "Taking a new step is what people fear most. 👣",
        "Bravery is not the absence of fear but action in spite of it. 💪",
        "Life shrinks or expands in proportion to one's courage. 🎈",
        "If your dreams don't scare you, they are too small. 🏔️",
        "Fear is a reaction. Courage is a decision. 🧠",
        "The world breaks everyone, and afterward, some are strong at the broken places. 💪",
        "I have not failed. I've just found 10,000 ways that won't work. 💡",
        "Failure is simply the opportunity to begin again, this time more intelligently. 🧠",
        "Our greatest glory is not in never falling, but in rising every time we fall. 🆙",
        "Success is not how high you have climbed, but how you make a positive difference to the world. 🌍",
        "Your playing small does not serve the world. 🌟",
        "The moment you give up is the moment you let someone else win. 🏆",
        
        // Self-Improvement (451-550)
        "Invest in yourself. It pays the best interest. 📈",
        "Be a student as long as you still have something to learn. 📚",
        "The more you learn, the more you earn. 💰",
        "If you don't sacrifice for what you want, what you want becomes the sacrifice. 🎯",
        "Growth is painful. Change is painful. But nothing is as painful as staying stuck. 😣",
        "Self-discipline begins with the mastery of your thoughts. 🧠",
        "Work on yourself more than you do on your job. 👤",
        "You can't pour from an empty cup. Take care of yourself first. ☕",
        "Be patient with yourself. Self-growth is tender; it's holy ground. 🌱",
        "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself. 🦋",
        "The only person you are destined to become is the person you decide to be. 🎯",
        "Life isn't about finding yourself. Life is about creating yourself. 🎨",
        "Your best teacher is your last mistake. 📖",
        "You can't go back and change the beginning, but you can start where you are and change the ending. 🔄",
        "Almost everything will work again if you unplug it for a few minutes, including you. 🔌",
        "Take care of your body. It's the only place you have to live. 🏠",
        "Transform your wounds into wisdom. 🧠",
        "Self-care is not self-indulgence, it is self-preservation. 💆",
        "Upgrade your mind constantly. 📈",
        "Read books, learn skills, build yourself. 📚",
        "Your current self is the result of your past decisions. Your future self depends on your present decisions. ⏳",
        "Be addicted to bettering yourself. 💪",
        "The best investment you can make is in yourself. 📈",
        "Never be a prisoner of your past. It was just a lesson, not a life sentence. 🗝️",
        "You cannot change what you are, only what you do. ✅",
        "Personal development is the belief that you are worth the effort, time, and energy needed to develop yourself. ❤️",
        "What lies behind us and what lies before us are tiny matters compared to what lies within us. 💎",
        "Strength grows in the moments when you think you can't go on but you keep going anyway. 💪",
        "Don't go through life, grow through life. 🌱",
        "Make yourself so valuable that you become irreplaceable. 💎",
        "Your vibe attracts your life. 🎯",
        "Know your worth, then add tax. 💰",
        "Work on being in love with the person in the mirror. 🪞",
        "Be so busy improving yourself that you have no time to criticize others. 🏃",
        "What you think, you become. What you feel, you attract. What you imagine, you create. 🧠",
        "Absorb what is useful, discard what is not. 📚",
        "Self-education is the key to success. 🔑",
        "Learning never exhausts the mind. 📖",
        "Develop a passion for learning. If you do, you will never cease to grow. 🌱",
        "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice. 🎁",
        "Anyone who stops learning is old, whether at twenty or eighty. 👴",
        "Live as if you were to die tomorrow. Learn as if you were to live forever. 📚",
        "The beautiful thing about learning is that nobody can take it away from you. 💎",
        "An investment in knowledge pays the best interest. 📈",
        "Education is not the filling of a pail, but the lighting of a fire. 🔥",
        "Tell me and I forget. Teach me and I remember. Involve me and I learn. 🎓",
        "The more that you read, the more things you will know. 📖",
        "Knowledge is power. Power is responsibility. 💪",
        "Learn something new every day. 🌅",
        "Growth is the only evidence of life. 🌱",
        
        // Positivity & Attitude (551-650)
        "Positive thinking will let you do everything better than negative thinking will. 🌟",
        "Your attitude determines your direction. 🧭",
        "The only disability in life is a bad attitude. 🛡️",
        "Happiness is a choice. Choose wisely. 😊",
        "Keep your face to the sunshine and you cannot see the shadow. ☀️",
        "A positive attitude causes a chain reaction of positive thoughts. 🔄",
        "Be positive, patient, and persistent. 💪",
        "Your smile is your logo, your personality is your business card. 😊",
        "The best is yet to come. 🌅",
        "Every day may not be good, but there's something good in every day. ✨",
        "Happiness is not by chance, but by choice. 🎯",
        "Think positive, be positive. 🌟",
        "Gratitude turns what we have into enough. 🙏",
        "Start each day with a grateful heart. ❤️",
        "Be thankful for what you have; you'll end up having more. 🎁",
        "Gratitude is the healthiest of all human emotions. 🌱",
        "When you arise in the morning, think of what a privilege it is to be alive. 🌅",
        "A grateful mind is a great mind which eventually attracts to itself great things. 🧲",
        "Happiness is not something you postpone for the future; it is something you design for the present. 🎨",
        "Enjoy the little things, for one day you may look back and realize they were the big things. 🌼",
        "Count your blessings, not your problems. 🙏",
        "Life is too short to be anything but happy. 😊",
        "Smile, breathe, and go slowly. 🐢",
        "Wherever you go, go with all your heart. ❤️",
        "Let your smile change the world, don't let the world change your smile. 😊",
        "Positive mind. Positive vibes. Positive life. 🌟",
        "Wake up every morning with the thought that something wonderful is about to happen. 🌅",
        "Be happy. It drives people crazy. 😊",
        "Life is short. Smile while you still have teeth. 😁",
        "Happiness blooms from within. 🌸",
        "Choose joy. 😊",
        "Good things are coming. 🌟",
        "Today is going to be a great day. 🌞",
        "Believe in the magic of new beginnings. ✨",
        "Every moment is a fresh beginning. 🌅",
        "New day, new blessings. 🎁",
        "The sun is new each day. ☀️",
        "Start over if you need to. 🔄",
        "It's never too late for a fresh start. 🌱",
        "Each morning we are born again. What we do today matters most. 🌅",
        "This is your year. 🎯",
        "Good vibes only. ✨",
        "Let go of what doesn't serve you. 🍃",
        "New week, new goals. 📅",
        "Monday is for fresh starts. 🆕",
        "Today is a gift. That's why we call it the present. 🎁",
        "Make every second count. ⏱️",
        "Live in the moment. 🌼",
        "Be present. Be patient. Be kind. 🌸",
        "Enjoy the journey. 🛤️",
        
        // Hard Work & Hustle (651-750)
        "Hustle in silence and let success make the noise. 🤫",
        "The dream is free. The hustle is sold separately. 💰",
        "Good things happen to those who hustle. 🏃",
        "Work like there is someone working 24 hours a day to take it all away from you. 💪",
        "Don't wait for opportunity, create it. 🛠️",
        "Grind while they sleep. Learn while they party. Save while they spend. 📈",
        "Success is no accident. 🎯",
        "There is no substitute for hard work. 💪",
        "The only place where success comes before work is in the dictionary. 📖",
        "I'm not lucky, I'm dedicated. 🔥",
        "Outwork everyone. 🏆",
        "Be so good they can't ignore you. ⭐",
        "The harder you work for something, the greater you'll feel when you achieve it. 🏆",
        "Work like you don't need the money. 💸",
        "While you're making excuses, someone else is making progress. 🏃",
        "Stop wishing, start doing. ✅",
        "The grind includes Friday nights and Sunday mornings. 📅",
        "Stay focused and never give up. 🎯",
        "Rise and grind. 🌅",
        "Work hard in silence, let success be your noise. 🤫",
        "Earn it. 💪",
        "Sacrifice today for a better tomorrow. 🌅",
        "Your only competition is who you were yesterday. 🆙",
        "Make things happen. ✅",
        "Every accomplishment starts with the decision to try. 🚀",
        "The pain you feel today will be the strength you feel tomorrow. 💪",
        "Work hard, play hard. 🎉",
        "Busy is a choice. 🎯",
        "If it was easy, everyone would do it. 🏔️",
        "Don't just exist. Live. 🌟",
        "Make money while you sleep. 💤",
        "Your network is your net worth. 🤝",
        "Opportunities don't happen. You create them. 🛠️",
        "Winners focus on winning. Losers focus on winners. 🏆",
        "Level up. 📈",
        "Stay grinding. 🔥",
        "Keep pushing. 💪",
        "Never stop hustling. 🏃",
        "Money doesn't grow on trees. You gotta shake the tree. 🌳",
        "Work until expensive becomes cheap. 💰",
        "Rich people stay rich by living like they're broke. 💵",
        "Think like a boss, act like a boss, become a boss. 👔",
        "Build your empire. 🏰",
        "Boss up or get bossed around. 👑",
        "Self-made. 💪",
        "Started from the bottom now we're here. 📈",
        "From nothing to something. 🚀",
        "Grind now, shine later. ✨",
        "Put in the work. 💪",
        "Commit to your goals. 🎯",
        
        // Leadership & Influence (751-850)
        "A leader is one who knows the way, goes the way, and shows the way. 🧭",
        "The greatest leader is not necessarily one who does the greatest things. 👑",
        "Leadership is not about being in charge. It's about taking care of those in your charge. 🤝",
        "Before you are a leader, success is all about growing yourself. 🌱",
        "Don't find fault, find a remedy. 🔧",
        "Example is not the main thing in influencing others. It is the only thing. 🎯",
        "Leadership is action, not position. ✅",
        "The task of leadership is not to put greatness into people, but to elicit it. ✨",
        "Lead from the front. 🏃",
        "Real leaders are ordinary people with extraordinary determination. 💪",
        "A good leader takes a little more than his share of the blame, and a little less than his share of the credit. ⚖️",
        "Be the leader you wish you had. 👔",
        "Leadership is about making others better as a result of your presence. 🌟",
        "The speed of the leader determines the rate of the pack. 🐺",
        "Leaders think and talk about solutions. Followers think and talk about problems. 💡",
        "True leadership stems from individuality that is honestly and sometimes imperfectly expressed. 💎",
        "If your actions inspire others to dream more, learn more, do more, you are a leader. 🚀",
        "Management is about arranging and telling. Leadership is about nurturing and enhancing. 🌱",
        "The mediocre teacher tells. The good teacher explains. The superior teacher demonstrates. The great teacher inspires. 🎓",
        "A genuine leader is not a searcher for consensus but a molder of consensus. 🛠️",
        "The very essence of leadership is that you have to have a vision. 👁️",
        "Leaders are made, not born. 🌱",
        "Become the kind of leader that people would follow voluntarily. 🤝",
        "It is better to lead from behind and to put others in front. 🎯",
        "Anyone can hold the helm when the sea is calm. ⛵",
        "Great leaders don't set out to be a leader. They set out to make a difference. 🌟",
        "The quality of a leader is reflected in the standards they set for themselves. 📏",
        "Innovation distinguishes between a leader and a follower. 💡",
        "To handle yourself, use your head; to handle others, use your heart. ❤️",
        "The best way to find yourself is to lose yourself in the service of others. 🤝",
        "You don't need a title to be a leader. 🏆",
        "Influence is about being the best version of yourself, not someone else. 🦋",
        "Your influence is a weapon. Use it wisely. ⚔️",
        "People may hear your words, but they feel your attitude. 💫",
        "The key to successful leadership is influence, not authority. 🔑",
        "Be someone's inspiration today. 🌟",
        "Lift as you climb. 🏔️",
        "Help others achieve their dreams and you will achieve yours. 🤝",
        "Success isn't just about what you accomplish, but what you inspire others to do. 🚀",
        "True leaders don't create followers, they create more leaders. 👑",
        "Be a voice, not an echo. 📢",
        "Stand for something or fall for anything. 🧱",
        "Your actions speak so loudly that I cannot hear what you are saying. 📣",
        "Let your light shine so brightly that others can see their way out of the dark. 💡",
        "You cannot lead anyone farther than you have gone yourself. 🛤️",
        "The best way to predict the future is to create it together. 🤝",
        "Empower others. 💪",
        "Share the credit. Own the blame. ⚖️",
        "A champion team will beat a team of champions. 🏆",
        "Together we achieve more. 🤝",
        
        // Vision & Dreams (851-950)
        "A dream without a plan is just a wish. 📝",
        "The future belongs to those who believe in the beauty of their dreams. 🌈",
        "All our dreams can come true if we have the courage to pursue them. 💪",
        "Dream as if you'll live forever. Live as if you'll die today. 🌟",
        "Vision without action is merely a dream. Action without vision just passes the time. 👁️",
        "Hold fast to dreams, for if dreams die, life is a broken-winged bird that cannot fly. 🐦",
        "Every great dream begins with a dreamer. 💭",
        "Dreams are the seeds of change. 🌱",
        "Never give up on a dream just because of the time it will take to accomplish it. ⏳",
        "You are never too old to dream a new dream. 🌲",
        "The ones who are crazy enough to think they can change the world are the ones that do. 🌍",
        "Dreams don't work unless you do. 💪",
        "Chase your dreams until you catch them, and then dream, catch, and dream again. 🏃",
        "Dream big, start small, act now. 🚀",
        "Your dream doesn't have an expiration date. 📅",
        "The biggest adventure you can take is to live the life of your dreams. 🎢",
        "Go confidently in the direction of your dreams. 🧭",
        "Follow your heart and your dreams will come true. ❤️",
        "You have to dream before your dreams can come true. 💭",
        "Dreams are extremely important. You can't do it unless you imagine it. 🎨",
        "Some people dream of success, while others wake up and work hard at it. 🌅",
        "Never let go of your dreams. 🎈",
        "Make your life a masterpiece. 🖼️",
        "Design the life you love. 🎨",
        "Create a life you can't wait to wake up to. 🌅",
        "Your vision will become clear only when you look into your heart. 👁️",
        "Everything starts with a dream. 💭",
        "Dream big, stay positive, work hard, and enjoy the journey. 🛤️",
        "Let your dreams be bigger than your fears. 🦋",
        "If you dream it, you can become it. 🌟",
        "Dream it. Build it. Live it. 🏗️",
        "Your life is your message to the world. Make it inspiring. 📣",
        "Be the architect of your own destiny. 🏛️",
        "You have the power to change your story. 📖",
        "Write your own future. ✍️",
        "The pen that writes your life story must be held in your own hand. 🖊️",
        "You are the author of your own life. 📚",
        "Make your own luck. 🍀",
        "Create your own path. 🛤️",
        "Don't follow the path. Blaze your own trail. 🔥",
        "The sky is not the limit. Your mind is. 🚀",
        "Shoot for the moon. Even if you miss, you'll land among the stars. 🌙",
        "Reach for the stars. ⭐",
        "Aim high. 🎯",
        "Think big, act bigger. 💭",
        "No dream is too big. 🏔️",
        "The only thing standing between you and your dream is the story you keep telling yourself. 📖",
        "Your future is created by what you do today. 🌅",
        "The question isn't who's going to let me; it's who's going to stop me. 💪",
        "Build your dreams or someone else will hire you to build theirs. 🏗️",
        
        // Final Motivation (951-1000)
        "You got this. 💪",
        "Keep going. 🏃",
        "Never give up. 🔥",
        "Stay strong. 💪",
        "Believe in yourself. 🌟",
        "You are enough. 💎",
        "This too shall pass. ☀️",
        "Tough times don't last, tough people do. 🦁",
        "One step at a time. 👣",
        "Progress, not perfection. 📈",
        "Every day is a new chance. 🌅",
        "You're closer than you think. 🏆",
        "Keep your head up. 👑",
        "The best is yet to come. ✨",
        "Your time will come. ⏰",
        "Stay patient. 🐢",
        "Trust the process. 🔄",
        "Everything happens for a reason. 🧩",
        "Stay true to yourself. 💎",
        "You matter. ❤️",
        "You are stronger than you know. 💪",
        "You can do hard things. 🏔️",
        "You are capable of amazing things. ✨",
        "Don't quit. 🏃",
        "Rise up. 🆙",
        "Be brave. 🦁",
        "Take the leap. 🦘",
        "Make it count. 🎯",
        "Live fully. 🌟",
        "Love deeply. ❤️",
        "Laugh often. 😊",
        "Be grateful. 🙏",
        "Stay humble. 🌱",
        "Work hard. 💪",
        "Dream big. 🚀",
        "Start now. ✅",
        "Be kind. 💕",
        "Stay focused. 🎯",
        "Keep learning. 📚",
        "Embrace change. 🔄",
        "Face your fears. 🦁",
        "Own your story. 📖",
        "Create your path. 🛤️",
        "Find your passion. 🔥",
        "Live your purpose. 🌟",
        "Made for greatness. 👑",
        "Born to succeed. 🏆",
        "Designed to win. 💪",
        "You are limitless. 🌊",
        "Go make it happen! 🚀"
    )
    
    // Keep existing lists for backwards compatibility
    val completionQuotes = motivationalQuotes.take(100)
    val homeDisplayQuotes = motivationalQuotes.drop(100).take(100)
    
    fun getCompletionQuote(): String = completionQuotes[Random.nextInt(completionQuotes.size)]
    fun getHomeQuote(): String = motivationalQuotes[Random.nextInt(motivationalQuotes.size)]
    
    // Dynamic variation system for even more variety
    private val prefixes = listOf("Remember:", "Always:", "Keep in mind:", "Today's Focus:", "Daily Wisdom:", "Pro Tip:", "Stay Sharp:")
    private val suffixes = listOf("You got this!", "Keep going!", "Stay unstoppable.", "Your time is now.", "Believe in the process.")

    fun getGrandQuote(): String {
        val base = getHomeQuote()
        return if (Random.nextBoolean()) {
            "${prefixes.random()} $base"
        } else {
            "$base ${suffixes.random()}"
        }
    }
    
    // Daily productivity tips - consistent per day
    private val dailyProductivityTips = listOf(
        "💡 Start with your hardest task first thing in the morning.",
        "⏰ Use the 2-minute rule: if it takes less than 2 minutes, do it now.",
        "🎯 Focus on ONE thing at a time. Multitasking kills productivity.",
        "📱 Turn off notifications during deep work sessions.",
        "🚶 Take a 5-minute walk every hour to refresh your mind.",
        "📝 Write down tomorrow's 3 goals before you sleep tonight.",
        "🧘 Start your day with 5 minutes of mindfulness or meditation.",
        "💧 Stay hydrated! Dehydration affects concentration.",
        "🌙 Get 7-8 hours of sleep. Rest is part of success.",
        "📵 Put your phone in another room during focus time.",
        "🎧 Try instrumental music or nature sounds while working.",
        "⏱️ Use the Pomodoro technique: 25 min work, 5 min break.",
        "📚 Spend 15 minutes learning something new every day.",
        "🗂️ Declutter your workspace. Clear space = clear mind.",
        "🚫 Learn to say NO to things that don't align with your goals.",
        "📆 Plan your week on Sunday evening.",
        "🌅 Wake up 30 minutes earlier for uninterrupted personal time.",
        "💪 Exercise in the morning for all-day energy boost.",
        "🎯 Break big goals into tiny, actionable steps.",
        "📊 Track your progress. What gets measured gets managed.",
        "🌿 Add a plant to your workspace for better focus.",
        "☕ Limit caffeine after 2 PM for better sleep.",
        "🔄 Batch similar tasks together to save mental energy.",
        "📖 Read for 10 minutes before bed instead of scrolling.",
        "🙏 Practice gratitude. Write 3 things you're grateful for.",
        "🎯 Review your goals every morning to stay on track.",
        "💭 Visualize your success for 2 minutes each morning.",
        "🏃 Move your body! Physical activity boosts brain power.",
        "📴 Schedule 'offline' time each day for deep thinking.",
        "🌟 Celebrate small wins. They lead to big victories.",
        "🧠 Take breaks when stuck. Answers often come during rest.",
        "📋 Keep a 'done' list to see your daily accomplishments."
    )
    
    fun getDailyTip(): String {
        val dayOfYear = java.time.LocalDate.now().dayOfYear
        return dailyProductivityTips[dayOfYear % dailyProductivityTips.size]
    }
}
